### ISSUE TITLE
Getting an error when compiling

### ISSUE THREAD

**Issue by PashaKagan** [xemulat/ReVancedPacker#12]
**Describe the bug**
Whenever I run the app, eventually it stops at this error.

AV is off, happens on 2 PCs.

Exception in thread "main" java.lang.NoSuchMethodError: java.util.jar.JarEntry.getRealName()Ljava/lang/String;
        at app.revanced.patcher.util.patch.implementation.JarPatchBundle$loadPatches$2.invoke(JarPatchBundle.kt:27)
        at app.revanced.patcher.util.patch.implementation.JarPatchBundle$loadPatches$2.invoke(JarPatchBundle.kt:13)
        at app.revanced.patcher.util.patch.util.StringIterator.next(StringIterator.kt:9)
        at app.revanced.patcher.util.patch.util.StringIterator.next(StringIterator.kt:3)
        at app.revanced.patcher.util.patch.base.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:19)
        at app.revanced.patcher.util.patch.implementation.JarPatchBundle.loadPatches(JarPatchBundle.kt:13)
        at app.revanced.utils.patcher.PatcherKt.addPatchesFiltered(Patcher.kt:22)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:122)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by xemulat** [comment]
Install Java 17 with Add To Pathenabled

**Comment by PashaKagan** [comment]
Thanks for the hint! It wasn't exactly that, but it pointed me to the right direction: there were conflicts with Java versions, so I cleaned up and started off fresh.
