### ISSUE TITLE
RVP.py: "Line 85: TypeError: type NoneType doesn't define __round__ method"

### ISSUE THREAD

**Issue by Spacellary** [xemulat/ReVancedPacker#46]
**Describe the bug**

**To Reproduce**
1. `python RVP.py`

**Expected behavior**
Proceeding normally to the next steps.

**Log:**
```
Traceback (most recent call last):
  File "D:\Browser-Downloads\Edge-Downloads-2023.1.2\RVP.py", line 255, in <module>
    main()
  File "D:\Browser-Downloads\Edge-Downloads-2023.1.2\RVP.py", line 85, in main
    f"Internet: {str(round(ping('github.com', unit='ms'), 2))}ms\n\n"
TypeError: type NoneType doesn't define __round__ method
```

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2

**Additional context**
Running RVP.py from latest 2.8 release

**Maybe a fix?**
Replacing line 85 with something like this `f"Internet: {str(round(ping('github.com', unit='ms'), 2)) if ping('github.com', unit='ms') is not None else 'N/A'}ms\n\n"` did allow me to proceed to next steps.

**Comment by xemulat** [comment]
get better internet

**Comment by xemulat** [comment]
nah but fr try restarting your router and pc

**Comment by Spacellary** [comment]
It's fine, if it can't be reproduced than it's an issue on my end then.
