### ISSUE TITLE
Unhandled Exception in script

### ISSUE THREAD

**Issue by mosfetish** [xemulat/ReVancedPacker#48]
Upon running RVP.exe, I get the following output:

```
Unhandled exception in script

Traceback (most recent call last):
  File "main.pyw", line 82, in <module>
  File "main.pyw", line 50, in getpatches
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Windows 10 Pro 64bit
Java 17.0.8+7
Python 3.9
RVP 3.2

I tried RVP 3.1 with same error.

**Comment by xemulat** [comment]
i'll fix it asap

**Comment by xemulat** [comment]
Error with the API changes btw

**Comment by xemulat** [comment]
fixed
